workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK (debug)
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
