name: gz_factory_monitoring
description: GZ Factory Monitoring - prototype (read-only demo)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Gz.PNG
