name: Build Android Debug APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Create android/ios folders if missing
        run: |
          if [ ! -d "Lib/android" ]; then
            flutter create .
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        # مسیر main.dart با توجه به پوشه‌ی Lib
        run: flutter build apk --debug -t Lib/main.dart

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
