name: Build Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ensure Android folder exists
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Copy Dart and assets
        run: |
          mkdir -p lib
          cp -R Lib/* lib/
          cp Gz.PNG lib/
          cp pubspec.yaml .

      - name: Get packages
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug -t lib/main.dart

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
